### ISSUE TITLE
Null reference exception in Shards.Table.cshtml on overhaul

### ISSUE THREAD

**Issue by Tony-Mc** [opserver/Opserver#113]
I'm on [overhaul](https://github.com/opserver/Opserver/tree/overhaul) branch commit [837711d](https://github.com/opserver/Opserver/commit/837711d2cab0a6c0d5f8fb548272375d8129e9a5) and I'm getting a NullReference exception on [line 8](https://github.com/opserver/Opserver/blob/overhaul/Opserver/Views/Elastic/Shards.Table.cshtml#L8) in `Shards.Table.cshtml`

I've got three Elastic clusters configured and those work great on `master`. This issue is more of a heads up in case you broke something.

Full stacktrace:
`at ASP._Page_Views_Elastic_Shards_Table_cshtml.Execute() in D:\Opserver\Opserver\Views\Elastic\Shards.Table.cshtml:line 8
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at StackExchange.Profiling.Mvc.WrappedView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP._Page_Views_Elastic_AllClusters_cshtml.Execute() in D:\Opserver\Opserver\Views\Elastic\AllClusters.cshtml:line 185
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.RunPage()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.RunPage()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at StackExchange.Profiling.Mvc.WrappedView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)`

**Comment by NickCraver** [comment]
Hmmm, I can't readily repro this - not sure how you'd get here with a null cluster. Can you give me some more details here - are there red/yellow cluster statuses? Do any other screens throw? What exact URL are you at?

**Comment by Tony-Mc** [comment]
Closing this because I can't reproduce that myself.

One of the clusters was down for sure and no connection could be made. I was debugging other stuff so there were several tabs open and it's possible that one of them might requested something while app was not initialized yet, although I have no idea how shards table could be requested in main screens.

**Comment by Tony-Mc** [comment]
So yesterday I got this once again. I was in main Elastic dashboard and one of the nodes was down. I did restart it and during the time when it was getting up I got the error again.

@NickCraver I will try to investigate this once I get some free time to setup elastic locally and debug the behavior. I might reopen this once I get some real info.

**Comment by NickCraver** [comment]
@Tony-Mc re-opening now since it's obviously a thing, must be a race on the polls - I'll take another look today.

**Comment by Tony-Mc** [comment]
No rush, it is not critical.

**Comment by NickCraver** [comment]
@Tony-Mc this was a case of me being stupid, fixed above!

**Comment by Tony-Mc** [comment]
I can confirm that it's working now.
