### ISSUE TITLE
View Details under SQL Volumes | View Files returns an error

### ISSUE THREAD

**Issue by WatersJohn** [opserver/Opserver#115]
This is likely just a hazard of using the overhaul branch, but thought I'd mention it.  Steps to repro:
1) Use the overhaul branch of Opserver
2) Click on a database server
3) Click 'view files' next to 'volumes'.
4) In the window that appears, click 'view detail'
5) The below error appears:
`
System.Web.HttpException (0x80004005): The controller for path '/sql/db-files' was not found or does not implement IController.
   at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
   at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
   at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

Issue appears to be in Views\SQL\Instance.DBFiles.cshtml, line 25 - refers to a nonexistent controller.

**Comment by NickCraver** [comment]
I'm not really sure where I pictured that link going - removing the link until if/when there is a more detailed file view.

**Comment by NickCraver** [comment]
Closing this out, but I welcome a new issue on discussions about what you'd be interested in for such a view!
