### ISSUE TITLE
Amazon RDS: 'databases'

### ISSUE THREAD

**Issue by win32nipuh** [opserver/Opserver#142]
I added my Amazon SQL Server  instance to opserver.
Click on 'databases'

```
Error

There was an error fetching server status from AmazonRDS\mydb: Unable to fetch from SQL: User 'guest' does not have permission to run DBCC LOGINFO. @    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)

```

RDS has some restrictionsfor user permissions, probably databases info can be retrieved using another way?

**Comment by JeevaDev7** [comment]
The issue occurs because Amazon RDS restricts the use of certain SQL Server commands and does not allow the DBCC LOGINFO command for users other than the rdsadmin user. This is part of RDS's security model to ensure stability and control over the managed environment.

The error message highlights that the guest user, likely being used by your Opserver configuration, does not have permission to execute the DBCC LOGINFO command.
