### ISSUE TITLE
NullReferenceException with Redis Master/Slave configuration

### ISSUE THREAD

**Issue by dcjulian29** [opserver/Opserver#218]
```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=App_Web_ns0qqqw0
  StackTrace:
       at ASP._Page_Views_Redis_Instance_cshtml.Execute() in C:\code\Opserver\Opserver\Views\Redis\Instance.cshtml:line 123
       at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
       at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
       at System.Web.WebPages.StartPage.RunPage()
       at System.Web.WebPages.StartPage.ExecutePageHierarchy()
       at System.Web.WebPages.StartPage.RunPage()
       at System.Web.WebPages.StartPage.ExecutePageHierarchy()
       at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
       at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
       at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
       at StackExchange.Profiling.Mvc.WrappedView.Render(ViewContext viewContext, TextWriter writer)
       at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList'1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList'1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
  InnerException: 
```

**My RedisSettings.json:**

``` javascript
{
  "allServers": {
    "name": "redis-prod1",
    "instances": [
      {
        "name": "Master",
        "port": "6379"
      },
      {
        "name": "Slave",
        "port": "6380"
      }
    ]
  },
  "Servers": [
    {"name":  "redis-prod1" }
  ] 
}
```

**Steps to Reproduce:**
1. Open Redis page in Internet Explorer 10.
2. Click on the "Master" link under the "Group" header.

**Other Observations**
The SlaveInstance of the Model.CurrentInstance object contains one element that is null.

**Other Information:**
- Git Branch: Overhaul
- Compiled in Visual Studio 2015 Update 3
- Running on Windows 10-1607
- Redis Server: 3.0.3  (one master and one slave)

**Comment by NickCraver** [comment]
A fix is in latest overhaul, thanks for the report!
