### ISSUE TITLE
Object reference error

### ISSUE THREAD

**Issue by djlaney3** [opserver/Opserver#222]
I pulled the latest version and am getting an error in StatusController.cs, line 82:
`{"Object reference not set to an instance of an object."}`,
Stack Trace:
```
   at StackExchange.Opserver.Controllers.StatusController.DefaultAction() in D:\Git\Opserver\Opserver\Controllers\StatusController.cs:line 82
   at StackExchange.Opserver.Controllers.HomeController.Home() in D:\Git\Opserver\Opserver\Controllers\HomeController.cs:line 17
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
```

**Comment by djlaney3** [comment]
I am using WMI with AD authentication.

**Comment by NickCraver** [comment]
Which branch are you using? I'm having trouble seeing where a null ref is there in overhaul.

**Comment by djlaney3** [comment]
Visual Studio tells me overhaul.  I pulled down a new zip and received the same error with my updated configs.  I tried to simplify my configs to see if that was the issue but it still occurred.

________________________________

**Comment by NickCraver** [comment]
I pushed some changes to modules just now - can you please try latest? At the least, we should have a better exception.

**Comment by djlaney3** [comment]
Still errors.  Here is the stack trace:
`   at StackExchange.Opserver.Data.Dashboard.DashboardModule.get_Enabled()
   at StackExchange.Opserver.Controllers.StatusController.DefaultAction() in C:\Users\dlaney\Downloads\Opserver-overhaul (2)\Opserver-overhaul\Opserver\Controllers\StatusController.cs:line 90
   at StackExchange.Opserver.Controllers.HomeController.Home() in C:\Users\dlaney\Downloads\Opserver-overhaul (2)\Opserver-overhaul\Opserver\Controllers\HomeController.cs:line 17
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()`
and the message: 
`The type initializer for 'StackExchange.Opserver.Data.Dashboard.DashboardModule' threw an exception.`

**Comment by NickCraver** [comment]
Okay, thanks for the debug info. I've got a handle on the actual issue now (the last error message was critical). I'm taking a look and fixing it now...if my laptop battery holds out. It's a result of all the async refactoring and one wait call in WMI.

**Comment by NickCraver** [comment]
@djlaney3 Can you please give latest one more shot?

**Comment by djlaney3** [comment]
Still Errors. 
Stack Trace:
`   at StackExchange.Opserver.Controllers.StatusController.DefaultAction() in D:\Git\Opserver\Opserver\Controllers\StatusController.cs:line 82
   at StackExchange.Opserver.Controllers.HomeController.Home() in D:\Git\Opserver\Opserver\Controllers\HomeController.cs:line 17
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()`

**Comment by djlaney3** [comment]
Also to note, the line: 
`if (s.Dashboard.Enabled && s.Dashboard.HasAccess())`
s.Dashboard is null when the error hits.  So i'm not sure if it is reading my dashboard settings file correctly.  I've dumbed it down to just 2 nodes, but the error still happens.

**Comment by djlaney3** [comment]
@NickCraver, I found the error.  My DashboardSettings.json had some erroneous characters, causing the file to not be read.  I was able to remedy that and all is working.  My apologies!

**Comment by NickCraver** [comment]
Thanks for helping track this down @djlaney3, I pushed a few fixes to that this doesn't hit others in such an unexpected way.
